email-domain: heustach.fr
emoji: 👻
domain: dev.heustach.fr
protocol: https
database-url: ${ssm:/heustach-dev/database-url}
esbuild:
  bundle: true
  minify: true
  sourcemap: true
  target: node20
  platform: node
  concurrency: 10
  external:
    - mysql2

serverlessTerminationProtection:
  stages:
    - prod

prune:
  automatic: true
  number: 1
